# ============================================
#  -------------SOURCE CODE STUB-------------
# ============================================
#  Stub Makefile that just point to the root
#  one for consistency
# ============================================


root=$(shell pwd)/../..

generate-memory:
	$(MAKE) -C $(root) $@

compile-source-code:
	$(MAKE) -C $(root) $@

link-executable:
	$(MAKE) -C $(root) $@

generate-binary:
	$(MAKE) -C $(root) $@

clean-memory-files:
	$(MAKE) -C $(root) $@


.PHONY: clean-memory-files compile-source-code generate-memory generate-binary 