# ┌                                                                                                   ┐
# │ This is a general RTL simulation script to load all relevant data for Questa on the project, I'm  │
# │ doing this to have a git tracked script that I can guarantee will work unlike the one generated   │
# │ by Quartus that often fails and breaks for reasons that are not entirely clear.                   │
# │                                                                                                   │
# │ For now it just loads everything it needs based on environment variables exported by the          │
# │ equivalent makefile target, maybe in the future it can select which files to load                 │
# │ programaticaly, but for now this will do                                                          │
# └                                                                                                   ┘


puts "---------------------"
puts "        START"
puts "---------------------"




# ╭─────────────────╮
# │ VARIABLES SETUP │
# ╰─────────────────╯

# projdir: base directory in which project files are referenced
if {[info exists env(PROJECT_DIR)]} {
	set projdir $env(PROJECT_DIR)
} else {
	puts "using fallback project directory"
	set projdir [pwd]
}
puts "project directory: $projdir"
puts ""


# plldir: pll folder where the main pll is generated by MegaWizard
set plldir $projdir/main_pll


# projdir: base directory in which project files are referenced
if {[info exists env(WAVE_DIR)]} {
	set wavedir $env(WAVE_DIR)
} else {
	puts "using fallback project directory"
	set wavedir [file join $projdir tcl_scripts]
}
puts "project directory: $wavedir"
puts ""


# Directory in which current running simulation happens
if {![info exists env(SIM_DIR)]} {

	# If none is defined on env defaults to standard Questa one
	set sim [file join $projdir simulation questa]

} else {
	set sim $env(SIM_DIR)
}
# If it doesn't exist for some reason creates it
if {![file isdirectory $sim]} {
	file mkdir $sim
}


# Directory for Verilog files that are user generated
if {![info exists env(RTL_SOURCE_DIR)]} {

	# It's an ok-ish fallback
	set verilog_source [file join $projdir rtl]
} else {
	set verilog_source env(RTL_SOURCE_DIR)
}

if {![file isdirectory $verilog_source]} {
	# It doesn't make sense to continue without this
	puts stderr "ERROR! Verilog files source folder doesn't exist, it's impossible to continue"
	exit 1
} else {
	puts "Verilog source folder found"
	puts "path: $verilog_source"
	puts ""
}


# Directory for testbench and related files
if {![info exists env(TB_SOURCE_DIR)]} {

	# another ok-ish fallback
	set tb_source [file join $projdir rtl tb]
} else {
	set verilog_source env(RTL_SOURCE_DIR)
}
if {![file isdirectory $tb_source]} {
	puts stderr "ERROR! Testbench files source folder doesn't exist, it's impossible to continue"
	puts stderr "path: $tb_source"
	exit 1
} else {
	puts "Testbench source folder found"
	puts "path: $tb_source"
	puts ""
}






# ╭───────────────╮
# │ QUESTA SCRIPT │
# ╰───────────────╯

puts "Loading Plataform Designer's .tcl script"
set QSYS_SIMDIR "$projdir/sys/simulation"
if {[catch {
	source "$QSYS_SIMDIR/mentor/msim_setup.tcl"
	com
} result]} {
	 puts stderr "ERROR!: $result"
	 puts stderr "INFO: $errorInfo"
	 exit 1
}
puts "Plataform Designer's .tcl executed"
puts ""








# ╭───────────────────╮
# │ CUSTOM COMPONENTS │
# ╰───────────────────╯

vlog -sv -work work +incdir+"$tb_source" "$tb_source/simple_rom.v"
vlog -sv -work work +incdir+"$tb_source" "$tb_source/shift_register_bank.v"
vlog -sv -work work +incdir+"$tb_source" "$tb_source/adc_mock.v"

vlog -sv -work work "$verilog_source/pulpino_qsys_test.v"

vlib pll
vmap pll pll

vlog -sv -work work +incdir+"$plldir" "$plldir/pll_sim/pll.vo"
vlog "$plldir/pll_sim/pll.vo"
vlog -sv -work pll +incdir+"$plldir" "$plldir/pll/pll_0002.v"


vlib sys
vmap sys sys
vlog -sv -work work +incdir+"$tb_source" "$tb_source/tbench.sv"
vlog -sv -work work "$tb_source/tbench.sv"







# ╭─────────────╮
# │ ELABORATION │
# ╰─────────────╯

puts "Starting Elaboration"
set TOP_LEVEL_NAME "work.tbench"
if {[catch {
	elab_debug
} result]} {
	 puts stderr "ERROR!: $result"
	 puts stderr "INFO: $errorInfo"
	 exit 1
}
puts "Elaboration ended"
puts ""







# ╭────────────────╮
# │ MAIN EXECUTION │
# ╰────────────────╯

if {[catch {
	do "$wavedir/main_waves.do"
	do "$wavedir/interruptions.do"
	do "$wavedir/core_signal.do"
} result]} {
	 puts stderr "ERROR!: $result"
	 puts stderr "INFO: $errorInfo"
	 exit 1
}

view structure
view signals
 run 200
