 #    ╔═══════════════════════════════════════════════════════════════════════════╗
 #    ║                                                                           ║
 #    ║ ██████╗ ████████╗██╗         ███████╗ ██████╗██████╗ ██╗██████╗ ████████╗ ║
 #    ║ ██╔══██╗╚══██╔══╝██║         ██╔════╝██╔════╝██╔══██╗██║██╔══██╗╚══██╔══╝ ║
 #    ║ ██████╔╝   ██║   ██║         ███████╗██║     ██████╔╝██║██████╔╝   ██║    ║
 #    ║ ██╔══██╗   ██║   ██║         ╚════██║██║     ██╔══██╗██║██╔═══╝    ██║    ║
 #    ║ ██║  ██║   ██║   ███████╗    ███████║╚██████╗██║  ██║██║██║        ██║    ║
 #    ║ ╚═╝  ╚═╝   ╚═╝   ╚══════╝    ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝    ║
 #    ║                                                                           ║
 #    ╚═══════════════════════════════════════════════════════════════════════════╝
 #
 # ┌                                                                                                   ┐
 # │ This is a general RTL simulation script to load all relevant data for Questa on the project, I'm  │
 # │ doing this to have a git tracked script that I can guarantee will work unlike the one generated   │
 # │ by Quartus that often fails and breaks for reasons that are not entirely clear.                   │
 # │                                                                                                   │
 # │ For now it just loads everything it needs based on environment variables exported by the          │
 # │ equivalent makefile target, maybe in the future it can select which files to load                 │
 # │ programaticaly, but for now this will do                                                          │
 # └                                                                                                   ┘



# ╭─────────────────╮
# │ VARIABLES SETUP │
# ╰─────────────────╯
# ┌                                                                          ┐
# │ Reads environment variables passed from makefile, create necessary paths │
# │ and prints important paths for debugging.                                │
# └                                                                          ┘

# projdir: base directory in which project files are referenced
if {[info exists env(PROJECT_DIR)]} {
	set projdir $env(PROJECT_DIR)
} else {
	puts "using fallback project directory"
	set projdir [pwd]
}
puts "project directory: $projdir"



# plldir: pll folder where the main pll is generated by MegaWizard
set plldir $projdir/main_pll



# Directory in which current running simulation happens
if {![info exists env(SIM_DIR)]} {
	
	# If none is defined on env defaults to standard Questa one
	set sim [file join $projdir simulation questa]

} else {
	set sim $env(SIM_DIR)
}
# If it doesn't exist for some reason creates it
if {![file isdirectory $sim]} {
	file mkdir $sim
}



# Directory in which Qsys generates simulation files
# I don't see a good reason for customizing this
set submodules [file join $projdir sys simulation submodules]
if {![file isdirectory $submodules]} {

	# It's impossible to load Qsys source files without this
	puts stderr "ERROR! Qsys Submodules source folder doesn't exist, it's impossible to continue"
	puts stderr $submodules
	exit 1
} else {
	puts "Qsys source folder found"
	puts "path: $submodules"
}



# Directory for Verilog files that are user generated
if {![info exists env(RTL_SOURCE_DIR)]} {

	# It's an ok-ish fallback
	set verilog_source [file join $projdir rtl]
} else {
	set verilog_source env(RTL_SOURCE_DIR)
}

if {![file isdirectory $verilog_source]} {

	# It doesn't make sense to continue without this
	puts stderr "ERROR! Verilog files source folder doesn't exist, it's impossible to continue"
	exit 1
} else {
	puts "Verilog source folder found"
	puts "path: $verilog_source"
}



# Directory for testbench and related files
if {![info exists env(TB_SOURCE_DIR)]} {

	# another ok-ish fallback
	set tb_source [file join $projdir rtl tb]
} else {
	set verilog_source env(RTL_SOURCE_DIR)
}
if {![file isdirectory $tb_source]} {
	puts stderr "ERROR! Testbench files source folder doesn't exist, it's impossible to continue"
	puts stderr "path: $tb_source"
	exit 1
} else {
	puts "Testbench source folder found"
	puts "path: $tb_source"
}


# Directory where Qsys creates simulation files for the designed platform
set iputf $sim/pulpino_qsys_test_iputf_libs
if {![file isdirectory $iputf]} {
	puts "creating iptuf file at: $iputf"
	file mkdir $iputf
}




#   ╭──────────────────────╮
#   │                      │
#   │ LIBRARIES DEFINITION │
#   │                      │
#   ╰──────────────────────╯
# ┌                                                                      ┐
# │ special directories are created with vlib, and then are mapped to a  │
# │ library for the simulation                                           │
# └                                                                      ┘


#Definicao inicial
vlib rtl_work
vmap work rtl_work




vlib $iputf/error_adapter_0
vmap error_adapter_0 $iputf/error_adapter_0

vlib $iputf/avalon_st_adapter
vmap avalon_st_adapter $iputf/avalon_st_adapter

vlib $iputf/rsp_mux_001
vmap rsp_mux_001 $iputf/rsp_mux_001

vlib $iputf/rsp_mux
vmap rsp_mux $iputf/rsp_mux

vlib $iputf/rsp_demux_012
vmap rsp_demux_012 $iputf/rsp_demux_012

vlib $iputf/rsp_demux
vmap rsp_demux $iputf/rsp_demux

vlib $iputf/cmd_mux_012
vmap cmd_mux_012 $iputf/cmd_mux_012

vlib $iputf/cmd_mux
vmap cmd_mux $iputf/cmd_mux

vlib $iputf/cmd_demux_001
vmap cmd_demux_001 $iputf/cmd_demux_001

vlib $iputf/cmd_demux
vmap cmd_demux $iputf/cmd_demux

vlib $iputf/pulpino_0_avalon_master_lsu_limiter
vmap pulpino_0_avalon_master_lsu_limiter $iputf/pulpino_0_avalon_master_lsu_limiter

vlib $iputf/router_015
vmap router_015 $iputf/router_015

vlib $iputf/router_014
vmap router_014 $iputf/router_014

vlib $iputf/router_002
vmap router_002 $iputf/router_002

vlib $iputf/router_001
vmap router_001 $iputf/router_001

vlib $iputf/router
vmap router $iputf/router


vlib $iputf/jtag_uart_0_avalon_jtag_slave_agent
vmap jtag_uart_0_avalon_jtag_slave_agent $iputf/jtag_uart_0_avalon_jtag_slave_agent

vlib $iputf/pulpino_0_avalon_master_lsu_agent
vmap pulpino_0_avalon_master_lsu_agent $iputf/pulpino_0_avalon_master_lsu_agent

vlib $iputf/onchip_memory2_0_s1_translator
vmap onchip_memory2_0_s1_translator $iputf/onchip_memory2_0_s1_translator

vlib $iputf/pulpino_0_avalon_master_instr_translator
vmap pulpino_0_avalon_master_instr_translator $iputf/pulpino_0_avalon_master_instr_translator

vlib $iputf/p2b_adapter
vmap p2b_adapter $iputf/p2b_adapter

vlib $iputf/b2p_adapter
vmap b2p_adapter $iputf/b2p_adapter

vlib $iputf/transacto
vmap transacto $iputf/transacto

vlib $iputf/p2b
vmap p2b $iputf/p2b

vlib $iputf/b2p
vmap b2p $iputf/b2p

vlib $iputf/fifo
vmap fifo $iputf/fifo

vlib $iputf/timing_adt
vmap timing_adt $iputf/timing_adt

vlib $iputf/jtag_phy_embedded_in_jtag_master
vmap jtag_phy_embedded_in_jtag_master $iputf/jtag_phy_embedded_in_jtag_master

vlib $iputf/rst_controller
vmap rst_controller $iputf/rst_controller

vlib $iputf/irq_mapper
vmap irq_mapper $iputf/irq_mapper

vlib $iputf/mm_interconnect_1
vmap mm_interconnect_1 $iputf/mm_interconnect_1

vlib $iputf/mm_interconnect_0
vmap mm_interconnect_0 $iputf/mm_interconnect_0

vlib $iputf/timer_0
vmap timer_0 $iputf/timer_0

vlib $iputf/pulpino_0
vmap pulpino_0 $iputf/pulpino_0

vlib $iputf/onchip_memory2_0
vmap onchip_memory2_0 $iputf/onchip_memory2_0

vlib $iputf/master_0
vmap master_0 $iputf/master_0

vlib $iputf/jtag_uart_0
vmap jtag_uart_0 $iputf/jtag_uart_0



#   ╭────────────╮
#   │ PIO SETUP  │
#   ╰────────────╯

# ┌                                                 ┐
# │ Since ALL PIO setups use the same parameters    │
# │ and configurations, they are all just instances │
# │ of 2 base PIOs, one for input and another for   │
# │ output                                          │
# └                                                 ┘


# === GPIO_A_R ===
# The same used by:
#   -GPIO_B_R
#   -GPIO_C_R

# Library definitions
vlib $iputf/GPIO_A_R
vmap GPIO_A_R $iputf/GPIO_A_R

# File Compilation
vlog -sv "$submodules/sys_GPIO_A_R.v"  -work GPIO_A_R


# === GPIO_A_S ===
# The same used by:
#   -GPIO_A_W
#   -GPIO_B_W
#   -GPIO_B_S
#   -GPIO_C0_W
#   -GPIO_C1_W
#   -GPIO_C2_W

# Library definitions
vlib $iputf/GPIO_A_S
vmap GPIO_A_S $iputf/GPIO_A_S

# File Compilation
vlog -sv "$submodules/sys_GPIO_A_S.v"  -work GPIO_A_S







#  ╭──────────────╮
#  │              │
#  │ MEMORY FILES │
#  │              │
#  ╰──────────────╯
#  ┌                                                                 ┐
#  │ Questa needs access to all memory files on the project, even if │
#  │ they are already defined on the components                      │
#  └                                                                 ┘

file copy -force $submodules/sys_onchip_memory2_0.hex ./






#   ╭───────────────────────╮
#   │                       │
#   │ COMPONENT COMPILATION │
#   │                       │
#   ╰───────────────────────╯
#   ┌                                                                          ┐
#   │ Component files (.v .sv .etc) are compiled into .vo files for simulation │
#   └                                                                          ┘

#------------------- Interconnection -----------------------
vlog -sv "$submodules/sys_mm_interconnect_1_avalon_st_adapter_error_adapter_0.sv" -work error_adapter_0                         
vlog     "$submodules/sys_mm_interconnect_1_avalon_st_adapter.v"                  -work avalon_st_adapter                       
vlog -sv "$submodules/sys_mm_interconnect_1_rsp_mux_001.sv"                       -work rsp_mux_001                             
vlog -sv "$submodules/altera_merlin_arbitrator.sv"                                -work rsp_mux_001                             
vlog -sv "$submodules/sys_mm_interconnect_1_rsp_mux.sv"                           -work rsp_mux                                 
vlog -sv "$submodules/altera_merlin_arbitrator.sv"                                -work rsp_mux                                 
vlog -sv "$submodules/sys_mm_interconnect_1_rsp_demux_012.sv"                     -work rsp_demux_012                           
vlog -sv "$submodules/sys_mm_interconnect_1_rsp_demux.sv"                         -work rsp_demux                               
vlog -sv "$submodules/sys_mm_interconnect_1_cmd_mux_012.sv"                       -work cmd_mux_012                             
vlog -sv "$submodules/altera_merlin_arbitrator.sv"                                -work cmd_mux_012                             
vlog -sv "$submodules/sys_mm_interconnect_1_cmd_mux.sv"                           -work cmd_mux                                 
vlog -sv "$submodules/altera_merlin_arbitrator.sv"                                -work cmd_mux                                 
vlog -sv "$submodules/sys_mm_interconnect_1_cmd_demux_001.sv"                     -work cmd_demux_001                           
vlog -sv "$submodules/sys_mm_interconnect_1_cmd_demux.sv"                         -work cmd_demux                               
vlog -sv "$submodules/altera_merlin_traffic_limiter.sv"                           -work pulpino_0_avalon_master_lsu_limiter     
vlog -sv "$submodules/altera_merlin_reorder_memory.sv"                            -work pulpino_0_avalon_master_lsu_limiter     
vlog -sv "$submodules/altera_avalon_sc_fifo.v"                                    -work pulpino_0_avalon_master_lsu_limiter     
vlog -sv "$submodules/altera_avalon_st_pipeline_base.v"                           -work pulpino_0_avalon_master_lsu_limiter     
vlog -sv "$submodules/sys_mm_interconnect_1_router_015.sv"                        -work router_015                              
vlog -sv "$submodules/sys_mm_interconnect_1_router_014.sv"                        -work router_014                              
vlog -sv "$submodules/sys_mm_interconnect_1_router_002.sv"                        -work router_002                              
vlog -sv "$submodules/sys_mm_interconnect_1_router_001.sv"                        -work router_001                              
vlog -sv "$submodules/sys_mm_interconnect_1_router.sv"                            -work router                                  
vlog -sv "$submodules/altera_merlin_slave_agent.sv"                               -work jtag_uart_0_avalon_jtag_slave_agent     
vlog -sv "$submodules/altera_merlin_burst_uncompressor.sv"                        -work jtag_uart_0_avalon_jtag_slave_agent     
vlog -sv "$submodules/altera_merlin_master_agent.sv"                              -work pulpino_0_avalon_master_lsu_agent       
vlog -sv "$submodules/altera_merlin_slave_translator.sv"                          -work onchip_memory2_0_s1_translator          
vlog -sv "$submodules/altera_merlin_master_translator.sv"                         -work pulpino_0_avalon_master_instr_translator
vlog -sv "$submodules/sys_master_0_p2b_adapter.sv"                                -work p2b_adapter                             
vlog -sv "$submodules/sys_master_0_b2p_adapter.sv"                                -work b2p_adapter                             
vlog     "$submodules/altera_avalon_packets_to_master.v"                          -work transacto                               
vlog     "$submodules/altera_avalon_st_packets_to_bytes.v"                        -work p2b                                     
vlog     "$submodules/altera_avalon_st_bytes_to_packets.v"                        -work b2p                                     
vlog     "$submodules/altera_avalon_sc_fifo.v"                                    -work fifo                                    
vlog -sv "$submodules/sys_master_0_timing_adt.sv"                                 -work timing_adt                              
vlog     "$submodules/altera_avalon_st_jtag_interface.v"                          -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_jtag_dc_streaming.v"                                 -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_jtag_sld_node.v"                                     -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_jtag_streaming.v"                                    -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_avalon_st_clock_crosser.v"                           -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_std_synchronizer_nocut.v"                            -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_avalon_st_pipeline_base.v"                           -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_avalon_st_idle_remover.v"                            -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_avalon_st_idle_inserter.v"                           -work jtag_phy_embedded_in_jtag_master        
vlog -sv "$submodules/altera_avalon_st_pipeline_stage.sv"                         -work jtag_phy_embedded_in_jtag_master        
vlog     "$submodules/altera_reset_controller.v"                                  -work rst_controller                          
vlog     "$submodules/altera_reset_synchronizer.v"                                -work rst_controller                          
vlog -sv "$submodules/sys_irq_mapper.sv"                                          -work irq_mapper                              
vlog     "$submodules/sys_mm_interconnect_1.v"                                    -work mm_interconnect_1                       
vlog     "$submodules/sys_mm_interconnect_0.v"                                    -work mm_interconnect_0                       




#--------------------TIMER----------------------------
vlog     "$submodules/sys_timer_0.v"                                              -work timer_0



#------------------- Processor -----------------------

vlog -sv "$submodules/adbg_config.sv"                                             -work pulpino_0
vlog -sv "$submodules/config.sv"                                                  -work pulpino_0
vlog -sv "$submodules/zeroriscy_config.sv"                                        -work pulpino_0
vlog -sv "$submodules/apb_bus.sv"                                                 -work pulpino_0
vlog -sv "$submodules/axi_bus.sv"                                                 -work pulpino_0
vlog -sv "$submodules/debug_bus.sv"                                               -work pulpino_0
vlog -sv "$submodules/cluster_clock_gating.sv"                                    -work pulpino_0
vlog -sv "$submodules/cluster_clock_inverter.sv"                                  -work pulpino_0
vlog -sv "$submodules/cluster_clock_mux2.sv"                                      -work pulpino_0
vlog -sv "$submodules/zeroriscy_defines.sv"                                       -work pulpino_0
vlog -sv "$submodules/zeroriscy_alu.sv"                                           -work pulpino_0
vlog -sv "$submodules/zeroriscy_compressed_decoder.sv"                            -work pulpino_0
vlog -sv "$submodules/zeroriscy_controller.sv"                                    -work pulpino_0
vlog -sv "$submodules/zeroriscy_core.sv"                                          -work pulpino_0
vlog -sv "$submodules/zeroriscy_cs_registers.sv"                                  -work pulpino_0
vlog -sv "$submodules/zeroriscy_debug_unit.sv"                                    -work pulpino_0
vlog -sv "$submodules/zeroriscy_decoder.sv"                                       -work pulpino_0
vlog -sv "$submodules/zeroriscy_ex_block.sv"                                      -work pulpino_0
vlog -sv "$submodules/zeroriscy_fetch_fifo.sv"                                    -work pulpino_0
vlog -sv "$submodules/zeroriscy_id_stage.sv"                                      -work pulpino_0
vlog -sv "$submodules/zeroriscy_if_stage.sv"                                      -work pulpino_0
vlog -sv "$submodules/zeroriscy_int_controller.sv"                                -work pulpino_0
vlog -sv "$submodules/zeroriscy_load_store_unit.sv"                               -work pulpino_0
vlog -sv "$submodules/zeroriscy_multdiv_fast.sv"                                  -work pulpino_0
vlog -sv "$submodules/zeroriscy_multdiv_slow.sv"                                  -work pulpino_0
vlog -sv "$submodules/zeroriscy_prefetch_buffer.sv"                               -work pulpino_0
vlog -sv "$submodules/zeroriscy_register_file_ff.sv"                              -work pulpino_0
vlog -sv "$submodules/core_top.sv"                                                -work pulpino_0


vlog     "$submodules/sys_onchip_memory2_0.v"                                     -work onchip_memory2_0
vlog     "$submodules/sys_master_0.v"                                             -work master_0


#------------------- JTAG Peripheral -----------------------
vlog -sv "$submodules/altera_avalon_jtag_uart.sv"                                 -work jtag_uart_0
vlog -sv "$submodules/altera_avalon_jtag_uart_log_module.sv"                      -work jtag_uart_0
vlog -sv "$submodules/altera_avalon_jtag_uart_scfifo_r.sv"                        -work jtag_uart_0
vlog -sv "$submodules/altera_avalon_jtag_uart_scfifo_w.sv"                        -work jtag_uart_0
vlog -sv "$submodules/altera_avalon_jtag_uart_sim_scfifo_r.sv"                    -work jtag_uart_0
vlog -sv "$submodules/altera_avalon_jtag_uart_sim_scfifo_w.sv"                    -work jtag_uart_0



#------------------- SYSTEM -----------------------
vlog     "$projdir/sys/simulation/sys.v"




#------------------- PLL -----------------------
vlog     "$plldir/pll_sim/pll.vo"



#------------------- ADC MOC ------------------
vlog -sv -work work +incdir+"$tb_source" "$tb_source/simple_rom.v"
vlog -sv -work work +incdir+"$tb_source" "$tb_source/shift_register_bank.v"
vlog -sv -work work +incdir+"$tb_source" "$tb_source/adc_mock.v"
file copy -force "$tb_source/fake_data.hex" ./

vlog -sv -work work +incdir+"$plldir" "$plldir/pll_sim/pll.vo"
vlog -sv -work work +incdir+"$verilog_source" "$verilog_source/pulpino_qsys_test.v"

vlib pll
vmap pll pll

vlog -sv -work pll +incdir+"$plldir" "$plldir/pll/pll_0002.v"

vlib sys
vmap sys sys

vlog -sv -work work +incdir+"$tb_source" "$tb_source/tbench.sv"





#  ╭──────────────╮
#  │              │
#  │ QUESTA START │
#  │              │
#  ╰──────────────╯
#  ┌                                                                                ┐
#  │ vsim starts Questa and we need a metric ton of arguments, one for each library │
#  └                                                                                ┘

vsim -t 1ps \
	 -L altera_ver \
	 -L lpm_ver \
	 -L sgate_ver \
	 -L altera_mf_ver \
	 -L altera_lnsim_ver \
	 -L cyclonev_ver \
	 -L cyclonev_hssi_ver \
	 -L cyclonev_pcie_hip_ver \
	 -L rtl_work \
	 -L work \
	 -L pll \
	 -L sys \
	 -L error_adapter_0 \
	 -L avalon_st_adapter \
	 -L rsp_mux_001 \
	 -L rsp_mux \
	 -L rsp_demux_012 \
	 -L rsp_demux \
	 -L cmd_mux_012 \
	 -L cmd_mux \
	 -L cmd_demux_001 \
	 -L cmd_demux \
	 -L pulpino_0_avalon_master_lsu_limiter \
	 -L router_015 \
	 -L router_014 \
	 -L router_002 \
	 -L router_001 \
	 -L router \
	 -L jtag_uart_0_avalon_jtag_slave_agent \
	 -L pulpino_0_avalon_master_lsu_agent \
	 -L onchip_memory2_0_s1_translator \
	 -L pulpino_0_avalon_master_instr_translator \
	 -L p2b_adapter \
	 -L b2p_adapter \
	 -L transacto \
	 -L p2b \
	 -L b2p \
	 -L fifo \
	 -L timing_adt \
	 -L jtag_phy_embedded_in_jtag_master \
	 -L rst_controller \
	 -L irq_mapper \
	 -L mm_interconnect_1 \
	 -L mm_interconnect_0 \
	 -L timer_0 \
	 -L pulpino_0 \
	 -L pio_out \
	 -L pio_in \
	 -L onchip_memory2_0 \
	 -L master_0 \
	 -L jtag_uart_0 \
	 -L GPIO_EXTRA \
	 -L GPIO_0 \
	 -L DEBUG \
	 -voptargs="+acc"  tbench

#  ╭────────────────────╮
#  │                    │
#  │ EXECUTION COMMANDS │
#  │                    │
#  ╰────────────────────╯
#  ┌                                                ┐
#  │ Here we send commands needed by the simulation │
#  └                                                ┘

add wave *
view structure
view signals
run --all
