
# ============================================
# ----------------QUARTUS STUB---------------
# ============================================
#  Stub Makefile that just point to the root
#  one for consistency
# ============================================

root=$(shell pwd)/..

rtl-sim:
	$(MAKE) -C $(root) $@

gate-sim:
	$(MAKE) -C $(root) $@

rtl-sim-gui:
	$(MAKE) -C $(root) $@

gate-sim-gui:
	$(MAKE) -C $(root) $@

compile-quartus:
	$(MAKE) -C $(root) $@

reload-memory:
	$(MAKE) -C $(root) $@

auto-testbench:
	$(MAKE) -C $(root) $@

quartus-gui:
	$(MAKE) -C $(root) $@

qsys-gui:
	$(MAKE) -C $(root) $@

compile-testbench:
	$(MAKE) -C $(root) $@

program-sof:
	$(MAKE) -C $(root) $@

synthesis:
	$(MAKE) -C $(root) $@

fitting:
	$(MAKE) -C $(root) $@

assembly:
	$(MAKE) -C $(root) $@

archive:
	$(MAKE) -C $(root) $@

clean-all-project:
	$(MAKE) -C $(root) $@

clean-project:
	$(MAKE) -C $(root) $@

clean-hardware-stamps:
	$(MAKE) -C $(root) $@

list-devices:
	$(MAKE) -C $(root) $@

clean-synthesis:
	$(MAKE) -C $(root) $@

clean-simulation:
	$(MAKE) -C $(root) $@


.PHONY: rtl-sim gate-sim rtl-sim-gui gate-sim-gui quartus-gui \
        timing-analysis compile-qsys reload-memory \
		qsys-gui clean-qsys clean-hardware-stamps archive \
		clean-simulation clean-qsys clean-synthesis \
		list-devices clean-all-project clean-project
