# ============================================
#  -----------VARIABLES FRAGMENT-------------
# ============================================
#  Make fragment with all definitions for
#  folders, paths and variables
# ============================================


#-------------------Project Directories-----------------

Q_DIR=$(PROJECT_DIR)/quartus_project
STAMPS_DIR=$(PROJECT_DIR)/.make_utils/stamps
COMPILER_SOURCE_DIR=$(PROJECT_DIR)/riscv-gnu-toolchain
TOOLCHAIN_DIR=$(PROJECT_DIR)/toolchain
TOOLS_DIR=$(PROJECT_DIR)/tools
QUESTA_DIR=$(Q_DIR)/simulation/questa
OUTPUT_DIR=$(Q_DIR)/output_files

SW_DIR=$(Q_DIR)/sw
MEM_DIR=$(SW_DIR)/mem_init
SRC_DIR=$(SW_DIR)/source_code




#------------------Hardware "Compilation"-------------------

# Qsys files
QSYS_FILE=$(Q_DIR)/$(QSYS_NAME)/synthesis/$(QSYS_NAME).qip
QSYS_SRC=$(Q_DIR)/$(QSYS_NAME).qsys
QIP_FILES := $(wildcard $(Q_DIR)/*.qip)

# Verilog sources
VERILOG_SOURCES := $(shell find $(Q_DIR) -type f \( -name '*.v' -o -name '*.sv' \))
TESTBENCH=$(Q_DIR)/rtl/tb/tbench.sv

# Other Quartus/Questa Related sources
SDC_FILES=$(Q_DIR)/$(PROJECT_NAME).sdc


# Important Files Generated by Quartus "Compilation'
rtl_sim_file=$(QUESTA_DIR)/$(PROJECT_NAME)_run_msim_rtl_verilog.do
gate_sim_file=$(QUESTA_DIR)/$(PROJECT_NAME)_run_msim_gate_verilog.do
END_SOF= $(OUTPUT_DIR)/$(PROJECT_NAME).sof
END_QSF= $(Q_DIR)/$(PROJECT_NAME).qsf





#-----------------Source Code--------------------

# Source files
C_SRCS = $(wildcard $(SRC_DIR)/*.c) 
S_SRCS = $(wildcard $(SRC_DIR)/*.s)
AS_SRCS = $(wildcard $(SRC_DIR)/*.S)
DEPS = $(wildcard $(SRC_DIR)/*.h)

# Object files
C_OBJS = $(patsubst $(SRC_DIR)/%.c,$(SRC_DIR)/%.o,$(C_SRCS))
S_OBJS = $(patsubst $(SRC_DIR)/%.s,$(SRC_DIR)/%.o,$(S_SRCS))
AS_OBJS = $(patsubst $(SRC_DIR)/%.S,$(SRC_DIR)/%.o,$(AS_SRCS))
OBJS = $(C_OBJS) $(S_OBJS) $(AS_OBJS)

# Compiled code file
ELF_INTERMEDIATE = $(SW_DIR)/bundle.elf

# Program Files
CC = $(TOOLCHAIN_DIR)/bin/riscv64-unknown-elf-gcc
ELFSIZE = $(TOOLCHAIN_DIR)/bin/riscv64-unknown-elf-size
OBJCOPY = $(TOOLCHAIN_DIR)/bin/riscv64-unknown-elf-objcopy

# Linker Script Path
LINKER_SCRIPT=$(SW_DIR)/link.riscv.ld

# Compilation Flags
CFLAGS = -Os $(TARGET_ARCH) -fdata-sections -ffunction-sections -fshort-enums -fgnu89-inline -Wall -MMD -MP
LDFLAGS = $(TARGET_ARCH) -Wl,--gc-sections --specs=nano.specs -nostartfiles

# Memory file prefix
MEM_NAME=sys_onchip_memory2_0
MEM = $(MEM_DIR)/$(MEM_NAME)

# Hex to binary Conversion
BIN2HEX = $(TOOLS_DIR)/bin2hex

# Export of the selected reloading method
export ALTERNATIVE_MEM_RELOAD




#-----------------Build Timestamps---------------------

# Toolchain
TOOLCHAIN_COMPILATION_STAMP=$(STAMPS_DIR)/toolchain_built

# Testbench
TB_COMPILE_STAMP=$(STAMPS_DIR)/testbench_compiled

# Memory Reloading
MEM_STAMP= $(STAMPS_DIR)/memory_stamp

# Complete Compilation 
DESIGN_COMPILE_STAMP = $(STAMPS_DIR)/quartus_compiled
SYNTHESIS_STAMP = $(STAMPS_DIR)/synthesis_stamp
ASSEMBLY_STAMP = $(STAMPS_DIR)/assembly_stamp
FITTING_STAMP = $(STAMPS_DIR)/fitting_stamp



